services:
  - type: static
    name: food-blood-sugar-analyzer-frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      # Admin routes - must come first
      - type: rewrite
        source: /admin/login
        destination: /index.html
      - type: rewrite
        source: /admin/*
        destination: /index.html
      # Login routes
      - type: rewrite
        source: /login/admin
        destination: /index.html
      - type: rewrite
        source: /login/*
        destination: /index.html
      # Other specific routes
      - type: rewrite
        source: /register
        destination: /index.html
      - type: rewrite
        source: /forgot-password
        destination: /index.html
      - type: rewrite
        source: /reset-password
        destination: /index.html
      - type: rewrite
        source: /profile
        destination: /index.html
      - type: rewrite
        source: /dashboard
        destination: /index.html
      - type: rewrite
        source: /glucose-readings
        destination: /index.html
      - type: rewrite
        source: /meals
        destination: /index.html
      - type: rewrite
        source: /activities
        destination: /index.html
      - type: rewrite
        source: /insulin-doses
        destination: /index.html
      # Catch all - must be last
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    envVars:
      - key: VITE_API_BASE_URL
        value: https://back-end-food-blood-sugar-analyzer.onrender.com
      - key: VITE_APP_NAME
        value: Food & Blood Sugar Analyzer
      - key: VITE_APP_VERSION
        value: 1.0.0 