services:
  - type: web
    name: food-blood-sugar-analyzer-frontend
    plan: free
    buildCommand: npm install && npm run build && cp serve.json dist/
    # Use SPA fallback and explicit config to ensure rewrites for deep links like /admin/login
    # NOTE: '-C' specifies the config file; '-c' is cache-control and would be incorrect here
    startCommand: npx serve -s dist -l $PORT -C dist/serve.json
    envVars:
      - key: VITE_API_BASE_URL
        value: https://back-end-food-blood-sugar-analyzer.onrender.com
      - key: VITE_APP_NAME
        value: Food & Blood Sugar Analyzer
      - key: VITE_APP_VERSION
        value: 1.0.0 