services:
  - type: web
    name: food-blood-sugar-analyzer-frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: VITE_API_BASE_URL
        value: https://back-end-food-blood-sugar-analyzer.onrender.com
      - key: VITE_APP_NAME
        value: Food & Blood Sugar Analyzer
      - key: VITE_APP_VERSION
        value: 1.0.0 